<?php
Redux::setSection( $opt_name, array(
    'title'      => __( 'Typography', THEMENAME ),
    'id'         => 'typography',
    'icon'       => 'el el-text-width',
    'desc'       => __( '', THEMENAME ),
    'fields'     => array(
        array(
            'id'            => 'opt-body-font',
            'type'          => 'typography',
            'title'         => __( 'Body font', THEMENAME ),
            'subtitle'      => __( 'Typography option with each property can be called individually.', THEMENAME ),
            'google'        => true,
            'font-backup'   => true,
            'letter-spacing'=> true,
            'output'        => array( 'body' ),
            'preview'       => array(
                'text'          => '1 2 3 4 5 6 7 8 9 0 A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z',
                'font-size'     => '24px',
                //'always_display'=> true,
            ),
            'units'         =>'px',
            'default'       => array(
                'color'         => '#878787',
                'font-size'     => '14px',
                'line-height'   => '25px',
                'font-family'   => 'Roboto',
                'font-weight'   => '400',
            ),
        ),
        array(
            'id'            => 'opt-h1-font',
            'type'          => 'typography',
            'title'         => __( 'H1', THEMENAME ),
            'google'        => true,
            'font-backup'   => true,
            'letter-spacing'=> true,
            'output'        => array( 'h1' ),
            'preview'       => array(
                'text'          => '1 2 3 4 5 6 7 8 9 0 A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z',
                'font-size'     => '24px',
                //'always_display'=> true,
            ),
            'units'         =>'px',
            'default'       => array(
                'color'         => '#AECA0B',
                'font-size'     => '30px',
                'line-height'   => '33px',
                'font-family'   => 'Roboto',
                'font-weight'   => '400',
            ),
        ),
        array(
            'id'            => 'opt-h2-font',
            'type'          => 'typography',
            'title'         => __( 'H2', THEMENAME ),
            'google'        => true,
            'font-backup'   => true,
            'letter-spacing'=> true,
            'output'        => array( 'h2' ),
            'preview'       => array(
                'text'          => '1 2 3 4 5 6 7 8 9 0 A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z',
                'font-size'     => '24px',
                //'always_display'=> true,
            ),
            'units'         =>'px',
            'default'       => array(
                'color'         => '#AECA0B',
                'font-size'     => '24px',
                'line-height'   => '25px',
                'font-family'   => 'Roboto',
                'font-weight'   => '400',
            ),
        ),
        array(
            'id'            => 'opt-h3-font',
            'type'          => 'typography',
            'title'         => __( 'H3', THEMENAME ),
            'google'        => true,
            'font-backup'   => true,
            'letter-spacing'=> true,
            'output'        => array( 'h3' ),
            'preview'       => array(
                'text'          => '1 2 3 4 5 6 7 8 9 0 A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z',
                'font-size'     => '24px',
                //'always_display'=> true,
            ),
            'units'         =>'px',
            'default'       => array(
                'color'         => '#AECA0B',
                'font-size'     => '20px',
                'line-height'   => '20px',
                'font-family'   => 'Roboto',
                'font-weight'   => '400',
            ),
        ),
        array(
            'id'            => 'opt-h4-font',
            'type'          => 'typography',
            'title'         => __( 'H4', THEMENAME ),
            'google'        => true,
            'font-backup'   => true,
            'letter-spacing'=> true,
            'output'        => array( 'h4' ),
            'preview'       => array(
                'text'          => '1 2 3 4 5 6 7 8 9 0 A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z',
                'font-size'     => '24px',
                //'always_display'=> true,
            ),
            'units'         =>'px',
            'default'       => array(
                'color'         => '#AECA0B',
                'font-size'     => '18px',
                'line-height'   => '18px',
                'font-family'   => 'Roboto',
                'font-weight'   => '400',
            ),
        ),
        array(
            'id'            => 'opt-h5-font',
            'type'          => 'typography',
            'title'         => __( 'H5', THEMENAME ),
            'google'        => true,
            'font-backup'   => true,
            'letter-spacing'=> true,
            'output'        => array( 'h5' ),
            'preview'       => array(
                'text'          => '1 2 3 4 5 6 7 8 9 0 A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z',
                'font-size'     => '24px',
                //'always_display'=> true,
            ),
            'units'         =>'px',
            'default'       => array(
                'color'         => '#AECA0B',
                'font-size'     => '16px',
                'line-height'   => '16px',
                'font-family'   => 'Roboto',
                'font-weight'   => '400',
            ),
        ),
        array(
            'id'            => 'opt-h6-font',
            'type'          => 'typography',
            'title'         => __( 'H6', THEMENAME ),
            'google'        => true,
            'font-backup'   => true,
            'letter-spacing'=> true,
            'output'        => array( 'h6' ),
            'preview'       => array(
                'text'          => '1 2 3 4 5 6 7 8 9 0 A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z',
                'font-size'     => '24px',
                //'always_display'=> true,
            ),
            'units'         =>'px',
            'default'       => array(
                'color'         => '#AECA0B',
                'font-size'     => '14px',
                'line-height'   => '18px',
                'font-family'   => 'Roboto',
                'font-weight'   => '400',
            ),
        ),
    )
) );